In [14]:
import csv
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib.ticker import LinearLocator, FormatStrFormatter
import numpy as np

Z = []
with open('lala.txt', 'rt') as csvfile:
    fitness_reader = csv.reader(csvfile, delimiter=',',quotechar='|')
    for row in fitness_reader:
        temp = []
        for el in row:
            temp.append(int(el))
        Z.append(temp)
    Z = np.array(Z)
    #print(Z)

[[ 1  1  2  3  4  5  4  3  2  1]
 [ 1  2  3  4  5  6  5  4  3  2]
 [ 2  3  4  5  6  7  6  5  4  3]
 [ 3  4  5  6  7  8  7  6  5  4]
 [ 4  5  6  7  8  9  8  7  6  5]
 [ 5  6  7  8  9 10  9  8  7  6]
 [ 4  5  6  7  8  9  8  7  6  5]
 [ 3  4  5  6  7  8  7  6  5  4]
 [ 2  3  4  5  6  7  6  5  4  3]
 [ 1  2  3  4  5  6  5  4  3  2]]


In [17]:
fig = plt.figure()
ax = fig.gca(projection='3d')

# Make data.
X = np.arange(1, 10, 1)
Y = np.arange(1, 10, 1)
X, Y = np.meshgrid(X, Y)
#https://en.wikipedia.org/wiki/Rosenbrock_function
#Z = (1-X)**2 + 1 *(Y-X**2)**2
# Plot the surface.
surf = ax.plot_surface(X, Y, Z, cmap=cm.gist_stern,
                       linewidth=0, antialiased=False)

# Customize the z axis.
#ax.set_zlim(-1.01, 1.01)
ax.zaxis.set_major_locator(LinearLocator(10))
ax.zaxis.set_major_formatter(FormatStrFormatter('%.02f'))

# Add a color bar which maps values to colors.
fig.colorbar(surf, shrink=0.5, aspect=5)

plt.show()

ValueError: shape mismatch: objects cannot be broadcast to a single shape

In [18]:
Z1 = []
with open('lala1.txt', 'rt') as csvfile:
    fitness_reader = csv.reader(csvfile, delimiter=',',quotechar='|')
    for row in fitness_reader:
        temp = []
        for el in row:
            temp.append(int(el))
        Z1.append(temp)
    Z1 = np.array(Z)
    #print(Z)
    
    fig = plt.figure()
    ax = fig.gca(projection='3d')

    # Make data.
    X1 = np.arange(1, 10, 1)
    Y1 = np.arange(1, 10, 1)
    X1, Y1 = np.meshgrid(X1, Y1)
    #https://en.wikipedia.org/wiki/Rosenbrock_function
    #Z = (1-X)**2 + 1 *(Y-X**2)**2
    # Plot the surface.
    surf = ax.plot_surface(X1, Y1, Z1, cmap=cm.gist_stern,
                           linewidth=0, antialiased=False)

    # Customize the z axis.
    #ax.set_zlim(-1.01, 1.01)
    ax.zaxis.set_major_locator(LinearLocator(10))
    ax.zaxis.set_major_formatter(FormatStrFormatter('%.02f'))

    # Add a color bar which maps values to colors.
    fig.colorbar(surf, shrink=0.5, aspect=5)

    plt.show()

ValueError: shape mismatch: objects cannot be broadcast to a single shape

In [19]:
Z2 = []
with open('lala2.txt', 'rt') as csvfile:
    fitness_reader = csv.reader(csvfile, delimiter=',',quotechar='|')
    for row in fitness_reader:
        temp = []
        for el in row:
            temp.append(int(el))
        Z2.append(temp)
    Z2 = np.array(Z)
    #print(Z)
    
    fig = plt.figure()
    ax = fig.gca(projection='3d')

    # Make data.
    X2 = np.arange(1, 10, 1)
    Y2 = np.arange(1, 10, 1)
    X2, Y2 = np.meshgrid(X2, Y2)
    #https://en.wikipedia.org/wiki/Rosenbrock_function
    #Z = (1-X)**2 + 1 *(Y-X**2)**2
    # Plot the surface.
    surf = ax.plot_surface(X2, Y2, Z2, cmap=cm.gist_stern,
                           linewidth=0, antialiased=False)

    # Customize the z axis.
    #ax.set_zlim(-1.01, 1.01)
    ax.zaxis.set_major_locator(LinearLocator(10))
    ax.zaxis.set_major_formatter(FormatStrFormatter('%.02f'))

    # Add a color bar which maps values to colors.
    fig.colorbar(surf, shrink=0.5, aspect=5)

    plt.show()

ValueError: shape mismatch: objects cannot be broadcast to a single shape